export const GalleryData = [
    {
        id:1,
        title:"anime",
        image:".../images/a1.jpeg"
    },
    {
        id:2,
        titile:"anime",
        image:"./images/anime-2.jpeg"
    },
    {
        id:3,
        titile:"art",
        image:"./images/art-1.jpeg"
    },
    {
        id:4,
        titile:"art",
        image:"./images/art-2.jpeg"
    },
    {
        id:5,
        titile:"games",
        image:"./images/games-1.jpeg"
    },
    {
        id:6,
        titile:"games",
        image:"./images/games-2.jpeg"
    },
    {
        id:7,
        titile:"photo",
        image:"./images/photo-1.jpeg"
    },
    {
        id:8,
        titile:"photo",
        image:"./images/photo-2.jpeg"
    },
    {
        id:9,
        titile:"3d",
        image:"./images/3d-1.jpeg"
    },
    {
        id:10,
        titile:"3d",
        image:"./images/3d-2.jpeg"
    },
    {
        id:11,
        titile:"sport",
        image:"./images/sport-1.jpeg"
    },
]